name = input ("Enter the your name is : ")
name2= input ('Enter the your name is : ')
name3 = input ('''Enter the your name is : ''')
print ("your name is :",(name))
print ("your name is :",(name2))
print ("your name is :",(name3))
print (type (name))
print (type (name2))
print (type (name3))