f=open("one.txt","a")
f.write("what is your name")
f1=open("one.txt","r")
f2=f1.read()
a=open("two.txt","a")
a.write("my name is dhruv")
a1=open("two.txt","r")
a2=a1.read()
c=open("three.txt","a")
c.write(a2)
c.write(f2)
print(c )
