print("*   * * *")
print("*   *")
print("*   *")
print("*   *")
print("* * * * *")
print("    *   *")
print("    *   *")
print("    *   *")
print("* * *   *")

print("123456789123456789")
print("12345\t*\t*")
print("======================\n")

print("*\t\t*\t*\t*\n\n*\t\t*\n\n*\t\t*\n\n*\t\t*\n\n*\t*\t*\t*\t*\n\n\t\t*\t\t*\n\n\t\t*\t\t*\n\n\t\t*\t\t*\n\n*\t*\t*\t\t*")