a = {"hitesh","kishan","dhruv","apple",123,11,22,33,456}
a1 = {"hitesh","kishan","dhruv","apple",123,456}
#a.remove("dhruv")
#a.add(123)
#a.remove(123)
#print(len(a))
#print(type(a))
#a.discard(123)
#a1=a.pop()
print(a.pop())
#print(dir(a))
#print(a.union(a1))
#print(a.intersection(a1))
#print(a.symmetric_difference(a1))
#print(dir(a))
c=a.clear()
print(c )
#print(a.isdisjoint(a1))
#print(a.isdisjoint(a1))
#print(a.issubset(a1 ))
#print(a.issuperset(a1))
#print(a)
#print(a.difference(a1)) 
#print(help(a))

#dir(a)
